spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1563081082
    url: jdbc:mysql://localhost:3306/carrot_hole?serverTimezone=UTC&useSSL=false
    username: root
#mybatis:
#  type-aliases-package: com.hust23se.carrothole #实体类取别名
#  configuration:
#    ## 下划线转驼峰配置
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
logging:
  level:
    root: info
    com.hust23se.carrothole: debug
  file:
    path: logs
server:
  port: 8080
